//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTienda.Backend.Modelo
{
    using ProyectoFede.MVVM.Base;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class clienta : PropertyChangedDataError
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public int idclienta { get; set; }
        [Required(ErrorMessage ="El nombre de la Clienta es Obligatoria")] public string nombre { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        [Required(ErrorMessage = "La fecha de Nacimiento de la Clienta es Obligatoria")] public System.DateTime fechaNacimiento { get; set; }
        public Nullable<double> dinero { get; set; }
        public Nullable<int> puntos { get; set; }
        public string mesNacimiento { get; set; }
    }
}
